version: '3.7'

services:
  nginx:
    image: nginx
    ports: 
      - 3030:80
  redis:
    image: redis
    ports: 
      - 6379:6379
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgres/data
    environment: 
      - POSTGRES_PASSWORD=password
volumes: 
  postgres-data: